cconst translations = {
  zh: {
    pageTitle: "岐黄研习台 - 中医知识学习平台",
    brand: "岐黄研习台",
    navLibrary: "中医库",
    navTheory: "中医理论",
    navFormula: "方剂",
    navHerb: "中药",
    toggleLabel: "English",
    heroEyebrow: "中医知识学习平台",
    heroTitle: "把理论、方剂、药材和临证笔记整理成一套能反复学习的知识库。",
    heroText: "先搭好平台骨架，后续你把方子、理论、医案、讲义发来，我可以继续帮你导入、分类、检索和生成专题页面。",
    enterLibrary: "进入中医库",
    viewPath: "查看学习路径",
    statTheory: "理论主题",
    statFormula: "方剂条目",
    statHerb: "中药条目",
    libraryTitle: "中医库入口",
    iconAll: "总",
    iconTheory: "理",
    iconFormula: "方",
    iconHerb: "药",
    entryAllTitle: "总览学习",
    entryAllText: "理论、方剂、中药一起检索",
    entryTheoryTitle: "中医理论",
    entryTheoryText: "阴阳、五行、脏腑、经络",
    entryFormulaTitle: "方剂库",
    entryFormulaText: "组成、功用、主治、学习提示",
    entryHerbTitle: "中药库",
    entryHerbText: "性味、归经、功效、配伍",
    searchLabel: "检索内容",
    searchPlaceholder: "搜索：桂枝汤、阴阳、甘草...",
    levelLabel: "学习阶段",
    noteTitle: "内容提示",
    noteText: "这里先放示例资料。正式上线前，我会按你提供的原文整理出处、分类、关键词和学习顺序。",
    detailEyebrow: "当前条目",
    detailTitle: "选择左侧内容开始学习",
    detailText: "点击任何理论、方剂或药材条目，这里会显示详细学习卡片。",
    pathTitle: "建议学习路径",
    pathOneTitle: "先立框架",
    pathOneText: "从阴阳、五行、藏象、经络这些基础概念开始，建立中医语言体系。",
    pathTwoTitle: "再看方药",
    pathTwoText: "把方剂拆成君臣佐使、功用主治、常见加减，和药材性味归经对应起来。",
    pathThreeTitle: "进入专题",
    pathThreeText: "后续可以按体质、病证、经典条文、医案等方式生成专题学习页。",
    disclaimer: "仅作学习整理，不替代专业诊疗建议。",
    resultUnit: "条",
    empty: "没有找到匹配内容。后续导入资料后，这里会自动扩展。",
    levels: {
      all: "全部阶段",
      beginner: "入门",
      advanced: "进阶",
      topic: "专题"
    },
    typeNames: {
      all: "全部资料",
      theory: "中医理论",
      formula: "方剂库",
      herb: "中药库"
    }
  },
  en: {
    pageTitle: "Qihuang Study Desk - Chinese Medicine Learning Platform",
    brand: "Qihuang Study Desk",
    navLibrary: "Library",
    navTheory: "Theory",
    navFormula: "Formulas",
    navHerb: "Herbs",
    toggleLabel: "中文",
    heroEyebrow: "Chinese Medicine Learning Platform",
    heroTitle: "A living knowledge base for theory, formulas, herbs, and clinical notes.",
    heroText: "The platform is ready for structured learning. Send your formulas, theories, cases, and lecture notes, and I can help organize them into searchable study pages.",
    enterLibrary: "Enter Library",
    viewPath: "View Learning Path",
    statTheory: "Theory Topics",
    statFormula: "Formula Entries",
    statHerb: "Herb Entries",
    libraryTitle: "Chinese Medicine Library",
    iconAll: "All",
    iconTheory: "Th",
    iconFormula: "Fx",
    iconHerb: "Hb",
    entryAllTitle: "Overview",
    entryAllText: "Search theories, formulas, and herbs together",
    entryTheoryTitle: "Theory",
    entryTheoryText: "Yin-yang, five phases, zang-fu, channels",
    entryFormulaTitle: "Formula Library",
    entryFormulaText: "Ingredients, actions, indications, study notes",
    entryHerbTitle: "Herb Library",
    entryHerbText: "Properties, channels, actions, pairings",
    searchLabel: "Search",
    searchPlaceholder: "Search: Gui Zhi Tang, yin-yang, licorice...",
    levelLabel: "Learning Stage",
    noteTitle: "Content Note",
    noteText: "These are sample entries. Before launch-grade publishing, I can organize your source text by attribution, category, keywords, and learning order.",
    detailEyebrow: "Current Entry",
    detailTitle: "Choose an item to begin",
    detailText: "Select any theory, formula, or herb entry to view its study card here.",
    pathTitle: "Suggested Learning Path",
    pathOneTitle: "Build the Framework",
